version: '3.1'

services:

  db:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: flowable_spring_boot
      MYSQL_USER: root
      MYSQL_PASSWORD: cjl14czx
